### PR TITLE
Change from CeCILL to BSD licence.

### PR DESCRIPTION
**Pull request by apdavison**
This proposed change is to make Sumatra more compatible with the general Python ecosystem (where BSD tends to be preferred) and to make it easier for others to use Sumatra as a library in their own tools.

### CODE REVIEW

**Comment by mattions** [comment]
+1 to the idea.

**Comment by timtroendle** [comment]
+1 from my side as well

**Comment by ashander** [comment]
Good idea



- Jaime

**Comment by maxalbert** [comment]
+1 from me

**Comment by apdavison** [comment]
ok, there seems to be a consensus on this, I'l merge it.

**Pull request merged**
