### PR TITLE
Rename README file so that github recognizes the markdown syntax

### PR DESCRIPTION
**Pull request by maxalbert**

### CODE REVIEW

**Comment by apdavison** [comment]
The README syntax is actually restructuredtext, not markdown (-:

(this is consistent with the use of Sphinx for the docs)

**Comment by maxalbert** [comment]
Ah, so can/should it be renamed README.rst? I guess it's not that important, but it's kind of nice if the Github page is properly displayed.

**Comment by apdavison** [comment]
Yes, the ".rst" suffix works. Do you want to go ahead and modify your PR?

**Comment by maxalbert** [comment]
Sure, done.

**Pull request merged**
