### PR TITLE
Feature/r compatibility -- Exectuable subclass and dependency_finder.r module (issue #29)

### PR DESCRIPTION
**Pull request by ashander**
RExectuable subclass is straightfoward

For dependency_finder submodule my approach is to call a custom R script that determines dependencies by using R `parse` on the script and finding calls to `library` or `require` with simple use of grep. Currently, it's called via subprocess.Popen (though this seems clunky as there should be a sumatra-wide wrapper for running the code no?). To consistently locate this R script, `setup.py` is modified to add an external_scripts directory. More details in commit below.

Test suites for the two affected modules are modified and pass.

Only tweak to doc sources is to add R section to find_dependencies.

Addresses Issue #29

### CODE REVIEW

**Comment by apdavison** [comment]
> called via subprocess.Popen (though this seems clunky as there should be a sumatra-wide wrapper for running the code no?)

Yes, there should be such a Sumatra-wide wrapper. Currently we're using different wrappers in different places (`tee`, `sarge`, etc.) and plain `subprocess` in others. I thought I created a ticket for this already, but I can't find it.

**Comment by apdavison** [comment]
This is great work. Many thanks!

**Comment by ashander** [comment]
Great. Glad I didn't miss something obvious!

**Comment by ashander** [comment]
Glad to contribute to a great project. Hope it can get some user interest
from the Rstats community

**Pull request merged**
