### PR TITLE
Add 'smt_profile' script

### PR DESCRIPTION
**Pull request by maxalbert**
This allows to run a Sumatra command with `cProfile` and outputs some profiling stats on the screen (and dumps them to a file). Example usage:

    smt_profile run -r "Test run" defaults.param

Sample output:

```
Wed Mar 11 23:17:32 2015    profiling_stats.prof

         273050 function calls (268822 primitive calls) in 11.281 seconds

   Ordered by: cumulative time
   List reduced from 2659 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   11.284   11.284 <string>:1(<module>)
        1    0.000    0.000   11.284   11.284 /home/albert/sumatra/sumatra/commands.py:314(run)
        1    0.000    0.000   11.277   11.277 /home/albert/sumatra/sumatra/projects.py:201(launch)
        1    0.000    0.000    8.571    8.571 /home/albert/sumatra/sumatra/records.py:125(run)
        1    0.000    0.000    8.570    8.570 /home/albert/sumatra/sumatra/launch.py:90(run)
        1    0.000    0.000    8.570    8.570 /home/albert/sumatra/sumatra/tee.py:55(system2)
      214    8.565    0.040    8.565    0.040 {method 'readline' of 'file' objects}
        1    0.000    0.000    1.559    1.559 /home/albert/sumatra/sumatra/projects.py:245(add_record)
        1    0.000    0.000    1.559    1.559 /home/albert/sumatra/sumatra/recordstore/django_store/__init__.py:187(save)
        1    0.000    0.000    1.144    1.144 /home/albert/sumatra/sumatra/projects.py:172(new_record)
        1    0.000    0.000    1.113    1.113 /home/albert/sumatra/sumatra/records.py:95(register)
        1    0.000    0.000    1.096    1.096 /home/albert/sumatra/sumatra/recordstore/django_store/__init__.py:156(_get_db_record)
       10    0.000    0.000    1.088    0.109 /home/albert/sumatra/sumatra/recordstore/django_store/__init__.py:135(_get_models)
        1    0.000    0.000    1.088    1.088 /home/albert/sumatra/sumatra/recordstore/django_store/__init__.py:97(configure)
        1    0.000    0.000    1.014    1.014 /home/albert/sumatra/sumatra/launch.py:130(get_platform_information)
        1    0.000    0.000    1.006    1.006 /home/albert/sumatra/sumatra/core.py:24(have_internet_connection)
```

I added this for profiling Sumatra itself (in particular, to debug the slow upgrade issue #214), but it can probably easily be adapted to profile the execution of user code, too (although not sure how useful that would be). I'm not even sure how useful it is to have such a `smt profile` command, but I thought I'd put it here to discuss it.

### CODE REVIEW

**Comment by apdavison** [comment]
As a profiler of Sumatra itself, this is really more of a developer tool. As such, I suggest making it into a standalone script in `sumatra/bin`, e.g. "smt_profile".

The idea of being able to easily profile user code is nice, but this implementation is too Python-specific. What would be needed is for each Executable subclass in the `programs` module to have an associated `Profiler` class.

**Comment by maxalbert** [comment]
Ok, I agree with this. Sumatra is not meant as a profiling tool anyway so to avoid feature creep I guess it's best to not support this for user code. I've moved the functionality into a separate script `bin/smt_profile` as you suggested. If you think it can be useful for others, feel free to merge it. But if it's too niche a use case then I don't mind not having it included in the main repository.

**Comment by apdavison** [comment]
I think you forgot to add `bin/smt_profile` to Git.

**Comment by maxalbert** [comment]
Whoops, thanks. I've added it now.

**Pull request merged**
