### PR TITLE
Added coveralls to Travis CI config

### PR DESCRIPTION
**Pull request by apdavison**
cf #236

### CODE REVIEW

**Comment by apdavison** [comment]
@ashander : since you created #236, could you take a quick look, and merge this if you're happy? (everything seems to be working, as you can see from the coveralls box in the timeline above!)

**Comment by ashander** [comment]
Awesome looks great

**Comment by ashander** [comment]
Looks good and from badge obviously working. Seems worth merging and can revisit config if something pops up. 

I don't have permission to merge though

**Comment by apdavison** [comment]
I thought I had added you as a member of the development team, so you should be able to merge (perhaps the e-mail invitation went to your spam folder?)

Anyway, I guess I can merge this now you've checked it out.

**Comment by ashander** [comment]
I don't see an invitation in spam. Do you mean you added me as a
'collaborator' on the main sumatra repo, or something else? If the former I
guess I should appear under sumatra > Settings > 'Collaborators' tab

**Comment by apdavison** [comment]
I added you to the "sumatra_developers" team in the "open-research" org. You might see the invitation at https://github.com/open-research

**Pull request merged**
