### PR TITLE
Updated developers' guide to reflect switch to Github

### PR DESCRIPTION
**Pull request by apdavison**
(plus other minor documentation updates)

### CODE REVIEW

**Comment by mattions** [comment]
+1

**Comment by maxalbert** [comment]
LGTM. For people less familiar with git it may be worth explicitly stating that "git pull upstream master" automatically merges any upstream changes (which "hg pull" didn't) and mentioning that "git fetch upstream" can be used to inspect changes before merging them. Also, is it worth encouraging people to use separate branches for any PRs? It does make things a lot tidier IMHO.

**Comment by wd15** [comment]
The docs build and look good to me.

**Comment by apdavison** [comment]
I've amended the commit to include the suggestion that people use separate branches. I didn't want to get into the differences between fetch and pull, I think it's perhaps too much detail.

**Pull request merged**
