### PR TITLE
Implements #190 (Drop dependency on simplejson).

### PR DESCRIPTION
**Pull request by apdavison**

### CODE REVIEW

**Comment by maxalbert** [comment]
The change itself looks good to me. Out of curiosity, what is the difference between the `json` and `simplejson` modules and why is the former preferable over the latter? (Or why was the `simplejson` module used in the first place?)

**Comment by apdavison** [comment]
The `simplejson` module was added to the Python standard library in Python 2.6 under the name `json`. Since Sumatra no longer supports Python 2.5 and earlier, we can drop use of `simplejson`.

**Comment by apdavison** [comment]
p.s. please go ahead and merge the pull request if you see no problems with it.

**Comment by maxalbert** [comment]
Ok. I wasn't sure how many people should take a look before merging. Also, currently some of the unit tests fail when I run them locally on my machine. I thought I'd try to fix this first so that I can run the tests on the PR before merging (btw, do we have Travis CI or something similar set up for Sumatra?). But in this case the change is probably trivial enough.

**Comment by apdavison** [comment]
Travis CI is on the way, later today I hope. For simple PRs like this one, I think a single reviewer is enough. For more complex changes, probably we would like at least two code reviews.

**Pull request merged**
