### PR TITLE
Added some tests of the web browser interface (smtweb) using Selenium

### PR DESCRIPTION
**Pull request by apdavison**
The test setup is rather slow, and most of the behaviour still needs to be tested, but this is at least a starting point. Will not yet run on Travis (I don't think), but should run locally following "pip install selenium".

### CODE REVIEW

**Comment by maxalbert** [comment]
I just tried it and it works for me so I'd be happy to merge it.

The only thing I personally don't like is the fact that it requires user input to confirm the deletion of the temporary directory at the end. I presume this is for debugging purposes? Would it be an option to have the script run `teardown()` by default but add a command line flag to switch this behaviour off? This would still allow debugging if something goes wrong but would also allow running the script non-interactively. But I'm not too fussed and happy to keep it this way if you prefer it.

**Comment by apdavison** [comment]
> The only thing I personally don't like is the fact that it requires user input to confirm the deletion of the temporary directory at the end. I presume this is for debugging purposes?

Yes, this is for debugging. However, this only happens if you run the script directly. With `nosetests` there is no prompt, it runs without user interaction.

**Comment by maxalbert** [comment]
Ah yes, I see. I just ran it through `nosetests` but got a few `AssertionError`s. Unfortunately I don't have time to investigate now. Can you reproduce these or is it something about my setup that's wrong?

Examples of failed assertions:
```
FAIL: test_webui.test_record_list
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/work/code/sumatra-dev/test/system/test_webui.py", line 137, in test_record_list
    assert_dict_contains_subset(expected, actual)
AssertionError: Mismatched values: u'label', expected: u'20151112-120816', actual: u'20151112-111822'
```

```
FAIL: test_webui.test_comparison_view
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/work/code/sumatra-dev/test/system/test_webui.py", line 187, in test_comparison_view
    assert "compare" in driver.current_url
AssertionError: 
```

```
FAIL: test_webui.test_data_detail_view
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/work/code/sumatra-dev/test/system/test_webui.py", line 194, in test_data_detail_view
    assert driver.current_url == "http://127.0.0.1:8765/ProjectGlass/{}/".format(utils.env["labels"][-1])
AssertionError: 
```

**Comment by maxalbert** [comment]
I tried to take another look at this PR, but when I re-ran the tests locally they failed. The first failure I encountered was due to some odd inconsistencies between record labels in `test_record_list()`, but I can't reproduce this now. However, now the tests fail inside `test_comparison_view()` (line 183) with the message: "StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up". @apdavison Would you mind having another look to see if anything changed since you submitted this PR and whether you can reproduce these failures? (You will probably also need to re-base the PR on latest master because the Travis setup has changed in the meantime.) Thanks!

**Comment by apdavison** [comment]
The inconsistencies in labels seem to be caused by an old instance of `smtweb` hanging around. As long as I ensure smtweb is not running, I don't see the inconsistent labels. I have rebased and fixed one new error I saw (seems similar to the one you saw about "StaleElement" but the error message was different), so I think this is ready to merge.

**Comment by apdavison** [comment]
Re-ran this with the latest selenium (3.5.0). I had to update Firefox and install [geckodriver](https://github.com/mozilla/geckodriver/releases), and kill all running instances of smtweb, but then all tests passed.

**Pull request merged**
