### PR TITLE
Added support for Django 1.7 and 1.8. Earlier versions no longer supported.

### PR DESCRIPTION
**Pull request by apdavison**
Implements #249.

Also fixes a couple of typos in the HTML templates.

### CODE REVIEW

**Comment by maxalbert** [comment]
I have no experience with Django, so can't comment on the PR itself. But I was wondering what impact (if any) this has on existing Sumatra projects. Are existing recordstores affected in any way? Do you anticipate any potential problems when users try to upgrade them?

**Comment by apdavison** [comment]
Users will have to upgrade their projects, as usual when a new version of Sumatra is released, i.e.

```
$ smt export
$ pip install -U sumatra
$ smt upgrade
```

It is my ambition to implement automatic upgrading soon, perhaps for the release after next (0.8). Django now supports database schema migration, so this should be fairly simple, but I'm going to stick with the manual upgrade process for the 0.7 release.

**Comment by callmeskywalker** [comment]
Hi. I am trying to install and test out Sumatra. I am trying to do so with Django 1.8.2.. I believe that I have properly installed all the requirements. I am getting errors however when I run "smt run" on a default.param file. I also get similar if not the exact error when running "smt list". I will add links to gist's for the errors. As well as a pip freeze for what I have installed. I thought this thread might be an OK place to put this. 
 
pip freeze - https://gist.github.com/callmeskywalker/8556e53731e299ceac84.js 
smt list - https://gist.github.com/callmeskywalker/92297d4c9535598b580c 
smt run default.param - https://gist.github.com/callmeskywalker/0308f772819f9a3746ba

I thought it could be related to the issues in this thread. 
Anyone have advice on what to do to fix the errors?
Even just a recommendation for better place to post this would be appreciated. 
Hope to be up and running soon.

**Comment by timtroendle** [comment]
@callmeskywalker, this is a pull request for support of Django 1.7 and higher in future versions of sumatra. With sumatra 0.6.0 as you are using it, you must install Django <= 1.6. You might want to look into #199.

**Comment by apdavison** [comment]
@callmeskywalker Any time you have a problem with Sumatra, feel free to create a ticket in this bug tracker, add a comment to an existing ticket if someone else already encountered the same problem, or send an e-mail to the mailing list: https://groups.google.com/forum/#!forum/sumatra-users

**Pull request merged**
