### PR TITLE
Update of the web interface

### PR DESCRIPTION
**Pull request by apdavison**
using Bootstrap 3 and Django class-based views; general code tidy.

This largely completes the work done by @Felix11H during GSoC, and removes no-longer used code from the previous implementation of the web interface (Using the Javascript DataTables library has saved a lot of code). I've also done a fair amount of renaming and reorganising.

Three main features are missing from version 0.6 of the web interface:

1. launching computations from the browser.
2. structured search.
3. visualization of code in the browser.

Unless anyone asks for it, I don't intend to restore (1). (2) and (3) will be re-added when time allows.

### CODE REVIEW

**Comment by timtroendle** [comment]
From a user perspective I figured the following things:
* selecting a record does not work: the records don't get highlighted. They also seem to not get selected as trying to select two records blind and clicking _compare_ doesn't do anything either.
* filtering records by tag from the menu bar does not work. There is simply nothing happening when clicked.
* in contrast to the documentation (text and screenshots), there is no search field in the record list

I've tested this with the most recent versions of Safari and Firefox.

**Comment by apdavison** [comment]
It sounds as though there is a problem with loading the Javascript. Can you activate the developer tools in Safari, or use Firebug with Firefox, and look at the error console?

**Comment by apdavison** [comment]
I think I found the problem - I had not updated setup.py to reflect the changed location of the Javascript and CSS files. Can you pull and try again?

**Comment by timtroendle** [comment]
Still the same unfortunately. Safari error console gives me always these log messages when loading the record list of my test project:

```
[Log] hidden: null (new-web-projects, line 325)
[Log] [ (new-web-projects, line 330)
Object
targets: null
visible: false
__proto__: Object
__defineGetter__: function __defineGetter__() {
__defineSetter__: function __defineSetter__() {
__lookupGetter__: function __lookupGetter__() {
__lookupSetter__: function __lookupSetter__() {
constructor: function Object() {
hasOwnProperty: function hasOwnProperty() {
isPrototypeOf: function isPrototypeOf() {
propertyIsEnumerable: function propertyIsEnumerable() {
toLocaleString: function toLocaleString() {
toString: function toString() {
valueOf: function valueOf() {
]
[Error] TypeError: null is not an object (evaluating 'hidden.forEach')
	ajax (jquery.min.js, line 4)
	(anonymous function) (new-web-projects, line 316)
	j (jquery.min.js, line 2)
	fireWith (jquery.min.js, line 2)
	ready (jquery.min.js, line 2)
	J (jquery.min.js, line 2)
```

**Comment by apdavison** [comment]
ok, can you try again?

**Comment by timtroendle** [comment]
yep, now it works just fine!

Just one more thing I stumbled upon: the compare feature relies on `numpy` which is not mentioned as a requirement. I guess it should be mentioned as an optional one and then there should be a helpful error message if a user tries to use that feature without having numpy installed.

**Comment by apdavison** [comment]
Good spot for the `numpy` dependency. It wasn't necessary, so I've removed it (and also written a unit test for that function).

**Pull request merged**
