### PR TITLE
Added a `diff()` method to `ParameterSet`

### PR DESCRIPTION
**Pull request by apdavison**

### CODE REVIEW

**Comment by ashander** [comment]
Seems useful. Design- and maintenence-wise, offloading param diffing to versioncontrol might be desirable. Is that possible? cc @maxalbert

**Comment by apdavison** [comment]
The problem with offloading param diffing to version control is that most VCS are intended for code, in which ordering of lines always matters, while often the order of parameters in a parameter set is unimportant, and tools may reorder parameters.

Secondarily, parameter sets often have a hierarchical structure, which VCS do not generally handle in a useful way.

**Comment by ashander** [comment]
Of course, that makes sense.

**Comment by apdavison** [comment]
@ashander @maxalbert @wd15 : please could one of you merge this?

**Comment by ashander** [comment]
Everything seems to make sense looking at the code. Coverage increases, and I don't see need for more documentation. Command line seems to work on small examples, BUT I'm having an issue with use from command line on my research code. 

The upshot is with slightly complex params as below (JSON param sets), `smt diff -l` prints out the whole set, not just differences. When I pass these to, e.g. `P4.diff(P5)` as in `test_parameters.py`, it seems to work. Here's a  snippet of `smt diff -l` output:

```sh
parameter differences:
  <label1>:
{
    "A": 0,
    "B": 2,
    "Cab": 0,
    "K0": 100000000,
    "Npop0": 10000,
    "Tlim": 200,
    "Vb": 0.0,
    "Ve": 0.5,
    "alpha": 0.0,
    "delta": 2.5,
    "fractgen": 5,
    "interp_alpha": false,
    "nrep": 500,
    "omega_Wmax": 1.15,
    "omegaz2": 25,
    "opt_Wmax": 0,
    "predict_alpha": true,
    "rho_dev_sel": 0.8,
    "rho_gen": false,
    "seed": 111,
    "sigma_xi2": 0.5,
    "t_vals": [
        3,
        4,
        5,
        20,
        40,
        50,
        75,
        100,
        200
    ],
    "var_a": 0.5,
    "var_ab": 0
}
  <label2>:
{
    "A": 0,
    "B": 2,
    "Cab": 0,
    "K0": 100000000,
    "Npop0": 10000,
    "Tlim": 200,
    "Vb": 0.05,
    "Ve": 0.5,
    "alpha": 0.8,
    "delta": 5,
    "exact": false,
    "fractgen": 5,
    "interp_alpha": false,
    "nrep": 500,
    "omega_Wmax": 1.15,
    "omegaz2": 25,
    "opt_Wmax": 0,
    "predict_alpha": false,
    "rho_dev_sel": 0.8,
    "rho_gen": false,
    "seed": 111,
    "sigma_xi2": 0.5,
    "t_vals": [
        5,
        10,
        20,
        40,
        80,
        100,
        150,
        200
    ],
    "var_a": 0.5,
    "var_ab": 0
}
```

**Comment by apdavison** [comment]
ok, I guess I only did half the job before. `smt diff -l` should now show just the differences, not the entirety of both parameter sets.

**Comment by ashander** [comment]
Great like this solves the issue.

**Pull request merged**
